### Exploratory data analysis with Pandas (Open Machine Learning Course)
data set : https://drive.google.com/file/d/1V4ayLAcdLsxgUSLS69vP_9w7jiRAmvyJ/view?usp=sharing

In [ ]:
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,.1f}'.format # пеобразование вывода больших  числовх значений в нормальный и разделение запятой групп цифр

In [ ]:
df = pd.read_csv("/content/adult.data.csv")
df.head()

age         workclass  fnlwgt  ... hours-per-week  native-country salary
0   39         State-gov   77516  ...             40   United-States  <=50K
1   50  Self-emp-not-inc   83311  ...             13   United-States  <=50K
2   38           Private  215646  ...             40   United-States  <=50K
3   53           Private  234721  ...             40   United-States  <=50K
4   28           Private  338409  ...             40            Cuba  <=50K

[5 rows x 15 columns]

In [ ]:
df.describe() # смотрим базовые числовые показатели

age      fnlwgt  ...  capital-loss  hours-per-week
count 32,561.0    32,561.0  ...      32,561.0        32,561.0
mean      38.6   189,778.4  ...          87.3            40.4
std       13.6   105,550.0  ...         403.0            12.3
min       17.0    12,285.0  ...           0.0             1.0
25%       28.0   117,827.0  ...           0.0            40.0
50%       37.0   178,356.0  ...           0.0            40.0
75%       48.0   237,051.0  ...           0.0            45.0
max       90.0 1,484,705.0  ...       4,356.0            99.0

[8 rows x 6 columns]

In [ ]:
df.info() # проверка на пустые значения

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  salary          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


## По заданию необходимо ответить на ряд вопросов:

1. Сколько мужчин и женщин представлены в этом наборе данных?

In [ ]:
df.groupby('sex')['sex'].count()

sex
Female    10771
Male      21790
Name: sex, dtype: int64

2. Каков средний возраст (возрастная характеристика) женщин?

In [ ]:
df[df['sex'] == 'Female']['age'].mean()

36.85823043357163

3. Каков процент граждан Германии?

In [ ]:
all = df['native-country'].count()
germany = df[df['native-country'] == 'Germany']['native-country'].count()
germany * 100 / all

0.42074874850281013

4-5. Каковы среднее значение и стандартное отклонение возраста для тех, кто зарабатывает более 50 тысяч в год (функция заработной платы), и тех, кто зарабатывает менее 50 тысяч в год? **

In [ ]:
print('Среднее значение возраста для тех, кто зарабатывает более 50 тысяч в год', df[df['salary'] == '>50K']['age'].mean())
print('Стандартное отклонение возраста для тех, кто зарабатывает более 50 тысяч в год', df[df['salary'] == '>50K']['age'].std())
print('Среднее значение возраста для тех, кто зарабатывает 50 и менее тысяч в год', df[df['salary'] == '<=50K']['age'].mean())
print('Стандартное отклонение возраста для тех, кто зарабатывает 50 и менее тысяч в год', df[df['salary'] == '<=50K']['age'].std())

Среднее значение возраста для тех, кто зарабатывает более 50 тысяч в год 44.24984058155847
Стандартное отклонение возраста для тех, кто зарабатывает более 50 тысяч в год 10.51902771985177
Среднее значение возраста для тех, кто зарабатывает 50 и менее тысяч в год 36.78373786407767
Стандартное отклонение возраста для тех, кто зарабатывает 50 и менее тысяч в год 14.020088490824813


6. Верно ли, что люди, которые зарабатывают более 50 тысяч, имеют как минимум среднее образование? (образование - бакалавриат, профшкола, ассистент, доцент, магистр или докторская степень)

In [ ]:
df[(df['salary'] == '>50K') & (df['education'] != 'Bachelors') & (df['education'] != 'Masters') & (df['education'] != 'Prof-school') & (df['education'] != 'Assoc-acdm') & (df['education'] != 'Assoc-voc') & (df['education'] != 'Doctorate')]

age         workclass  fnlwgt  ... hours-per-week  native-country salary
7       52  Self-emp-not-inc  209642  ...             45   United-States   >50K
10      37           Private  280464  ...             80   United-States   >50K
27      54                 ?  180211  ...             60           South   >50K
38      31           Private   84154  ...             38               ?   >50K
55      43           Private  237993  ...             40   United-States   >50K
...    ...               ...     ...  ...            ...             ...    ...
32510   39           Private  107302  ...             45               ?   >50K
32518   57         Local-gov  110417  ...             40   United-States   >50K
32519   46           Private  364548  ...             48   United-States   >50K
32557   40           Private  154374  ...             40   United-States   >50K
32560   52      Self-emp-inc  287927  ...             40   United-States   >50K

[3306 rows x 15 columns]

Как мы видим - среди выборки есть как минимум выпускники средней школы. Утверждение не верное.

7. Отображение статистики возраста для каждой расы (признак расы) и каждого пола (признак пола). Используйте groupby () и describe (). Найдите максимальный возраст мужчин амер-индийско-эскимосской расы. 

In [ ]:
new_df = df[df['sex'] == 'Male'] # оставляем в таблице только мужчин
df.groupby(new_df['race'])['age'].describe()

count  mean  std  min  25%  50%  75%  max
race                                                           
Amer-Indian-Eskimo    192.0  37.2 12.0 17.0 28.0 35.0 45.0 82.0
Asian-Pac-Islander    693.0  39.1 12.9 18.0 29.0 37.0 46.0 90.0
Black               1,569.0  37.7 12.9 17.0 27.0 36.0 46.0 90.0
Other                 162.0  34.7 11.4 17.0 26.0 32.0 42.0 77.0
White              19,174.0  39.7 13.4 17.0 29.0 38.0 49.0 90.0

Максимальный возраст мужчин амер-индийско-эскимосской расы: 82 года

8. Среди кого больше доля тех, кто много зарабатывает (> 50K): женатые или холостые мужчины (признак семейного положения)? Женатыми считаются те, кто имеет семейное положение, начиная с женат (женат-гражданский-супруг, женат-супруг-отсутствующий или женат-AF-супруг), остальные считаются холостяками.

In [ ]:
new_df = df[(df['sex'] == 'Male') & (df['salary'] == '>50K')] # оставляем в таблице только мужчин с заработком от 50К

count_married = new_df[(new_df['marital-status'] == 'Married-civ-spouse') | (new_df['marital-status'] == 'Married-spouse-absent') | (new_df['marital-status'] == 'Married-AF-spouse')]['marital-status'].count()
count_not_married = new_df['marital-status'].count() - count_married
if count_married > count_not_married:
  print('Женатые чаще зарабатывают больше 50К, чем холостые (женатые -', count_married, ') (холостые -', count_not_married, ')')
else:
  print('Холостые чаще зарабатывают больше 50К, чем женатые (женатые -', count_married, ') (холостые -', count_not_married, ')') 

Женатые чаще зарабатывают больше 50К, чем холостые (женатые - 5965 ) (холостые - 697 )


9. Какое максимальное количество часов человек работает в неделю (функция часов в неделю)? Сколько людей работают такое количество часов и каков процент среди них тех, кто много зарабатывает (> 50 тысяч)?

In [ ]:
max_work = df['hours-per-week'].max()
print('Человек работает максимальное количество (чесов в неделю):', max_work)
max_work_caunt = df[df['hours-per-week'] == max_work]['hours-per-week'].count()
print('Количество людей, кто работает', max_work, 'часов в неделю -', max_work_caunt)
max_work_proc = df[(df['hours-per-week'] == max_work) & (df['salary'] == '>50K')]['hours-per-week'].count() * 100 / max_work_caunt
print('Процент людей, кто работает', max_work, 'часов в неделю и заработывает более 50К:', max_work_proc)

Человек работает максимальное количество (чесов в неделю): 99
Количество людей, кто работает 99 часов в неделю - 85
Процент людей, кто работает 99 часов в неделю и заработывает более 50К: 29.41176470588235


10. Подсчитайте среднее время работы (часы в неделю) для тех, кто зарабатывает мало и много (зарплата) для каждой страны (родной страны). Что это будет для Японии?

In [ ]:
df_little_salary = df[(df['salary'] == '<=50K')]
df_lot_salary = df[(df['salary'] == '>50K')]
# pd.crosstab(df['salary'], df['native-country'])
df_little_salary.groupby(["native-country" ])['hours-per-week'].mean(), df_lot_salary.groupby(["native-country" ])['hours-per-week'].mean()


(native-country
 ?                            40.2
 Cambodia                     41.4
 Canada                       37.9
 China                        37.4
 Columbia                     38.7
 Cuba                         38.0
 Dominican-Republic           42.3
 Ecuador                      38.0
 El-Salvador                  36.0
 England                      40.5
 France                       41.1
 Germany                      39.1
 Greece                       41.8
 Guatemala                    39.4
 Haiti                        36.3
 Holand-Netherlands           40.0
 Honduras                     34.3
 Hong                         39.1
 Hungary                      31.3
 India                        38.2
 Iran                         41.4
 Ireland                      40.9
 Italy                        39.6
 Jamaica                      38.2
 Japan                        41.0
 Laos                         40.4
 Mexico                       40.0
 Nicaragua                    36.1
 Out

Для Японии. Среднее время работы для тех кто много зарабатывает: 48.0 часов в неделю. Среднее время работы для тех кто мало зарабатывает: 41.0 час в неделю.